export interface ParcelDetails {
    merchant_id: number,
    weightlbs: number,
    recipient_name: string,
    recipient_street_address: string,
    recipient_address_line2: string,
    recipient_address_line3: string,
    recipient_city: string,
    recipient_parish_state: string,
    recipient_post_office: string,
    recipient_zip_code: string,
    recipient_address_code: string,
    recipient_country: string,
    recipient_email: string,
    recipient_phone: string,
    customer_id: number,
    delivery_time_type: string,
    weight: number,
    delivery_type: string,
    package_status: string,
    created_by: number
}

export interface ParcelDetailsResponse {
    created_by: number,
    customer_id: number,
    date_created: Date,
    delivery_distance: number,
    delivery_time_type: string,
    delivery_type: string,
    id: string,
    merchant_id: number,
    package_status: string,
    recipient_address_code: string,
    recipient_address_line2: string,
    recipient_address_line3: string,
    recipient_city: string,
    recipient_country: string,
    recipient_email: string,
    recipient_name: string,
    recipient_parish_state: string,
    recipient_phone: string,
    recipient_post_office: string,
    recipient_street_address: string,
    recipient_zip_code: string,
    sender_address_code: string,
    sender_address_line2: string,
    sender_address_line3: string,
    sender_city: string,
    sender_country: string,
    sender_email: string,
    sender_name: string,
    sender_parish_state: string,
    sender_phone: string,
    sender_post_office: string,
    sender_street_address: string,
    sender_zip_code: string,
    weight: number
}


export interface PostOfficeParcelPayload {
    recipient_name: string,
    recipient_address: string,
    full_address_code: string,
    parcel_type: string,
    received_date: string,
    received_by: number,
    postal_location: string,
    addressline1: string,
    addressline2: string,
    city: string,
    parish: string,
    postalzone: string,
    smartcode: string
}